version: '3.8'

networks:
  app-network:

volumes:
  named-vol:

services:
  webserver:
    image: nginx:1.21.6-alpine
    container_name: webserver-hust
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:

  backend:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: backend-hust
    volumes:
      - ./:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:
  db-mysql:
    container_name: db-mysql-hust
    image: mysql
    volumes:
      - named-vol:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
    ports:
      - 8992:3306
    networks:
      app-network:
  php-myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin-hust
    environment:
      - "PMA_HOST=db-mysql"
    ports:
      - 7788:80
    networks:
      app-network:
    
